window.PREGUNTAS_ADULTO = {
  verdades: [
    '¿Cuál es tu fantasía sexual más oscura que jamás le has contado a nadie? Hoy la cuentas con todos los detalles.',
    '¿Cuál es el lugar más atrevido donde has tenido sexo? ¿Había riesgo real de que los vieran?',
    '¿Sientes atracción física por alguien en esta habitación ahora mismo? Di quién es y qué harías con esa persona.',
    '¿Cuál fue la propuesta sexual más indecente que te han hecho? ¿La rechazaste o la aceptaste y por qué?',
    '¿Tienes fotos, videos o conversaciones comprometedoras escondidas en tu teléfono? ¿De quién y qué tan explícitas son?',
    '¿Cuál es tu kink o fetiche más sucio? El que menos imaginarían de ti. Sin eufemismos.',
    '¿Cuál es la cosa más sexual y salvaje que has hecho en una fiesta? ¿Alguien lo sabe?',
    '¿Tienes conversaciones de sexteo o fotos íntimas que te destruirían si alguien las viera? ¿De quién?',
    '¿Con quién de este grupo tendrías sexo esta noche si nadie pudiera hablar de ello jamás?',
    '¿Cuál fue tu peor — o mejor — decisión sexual bajo el efecto del alcohol? Todos los detalles.',
    '¿Cuál es tu secreto sexual más guardado que si lo dijeras aquí cambiaría la forma en que te ven para siempre?',
    '¿Cuál fue la situación sexual más comprometedora en la que te han sorprendido en pleno acto?',
    '¿Con cuántas personas has tenido sexo? Sé honesto/a. ¿Cuál fue la más memorable y por qué?',
    '¿Cuál es tu posición favorita y la que más te hace perder la cabeza? Descríbela sin omitir nada.',
    '¿Alguna vez te grabaron o te grabaste durante el sexo? ¿Dónde está ese material ahora?',
    '¿Qué parte del cuerpo de alguien de este grupo te ha llamado la atención de forma sexual? Dilo sin miedo.',
    '¿Has tenido sexo en algún lugar donde claramente podían verlos y eso te excitó más? ¿Dónde fue?',
    '¿Cuál es la foto o mensaje más explícito que has enviado? ¿A quién? ¿Qué tan hot era exactamente?',
    '¿Con quién de este grupo tendrías algo sexual si estuvieran solos esta noche? ¿Qué harían exactamente?',
    '¿Cuál es tu secreto sexual más íntimo que nunca le has confesado a ninguna pareja?',
    '¿Cuál fue el momento más gracioso o incómodo que tuviste durante el sexo?',
    '¿Qué es lo que más te gusta que te hagan en la cama? Sé específico/a: zona, técnica, todo.',
    '¿Alguna vez sentiste atracción sexual por alguien del mismo sexo? ¿Actuaste en consecuencia?',
    '¿Cuánto tiempo necesitas conocer a alguien para acostarte? ¿Cuál fue tu récord más rápido?',
    '¿Qué es lo que más te enciende de otra persona? La cosa que hace que quieras arrancarle la ropa.',
    '¿Alguna vez fingiste un orgasmo? ¿Cuántas veces, con quién y por qué no dijiste la verdad?',
    '¿Qué harías exactamente con alguien de este grupo si tuvieras 1 hora solos y sin consecuencias?',
    '¿Cuál es la cosa más atrevida y explícita que has hecho con una pareja que te dejó sin palabras?',
    '¿Has tenido algo sexual con alguien de tu círculo de amigos y lo mantuviste en secreto? ¿Quién fue?',
    '¿Qué parte de tu cuerpo te gustaría que alguien de este grupo tocara ahora mismo? Señálala si te atreves.',
    '¿Cuál es tu experiencia sexual más hot e intensa? Cuenta todos los detalles sin omitir nada.',
    '¿Qué es lo que nunca volverías a hacer en la cama y por qué quedó en esa lista?',
    '¿Cuál es el lugar público más atrevido donde has hecho algo sexual que definitivamente no debías?',
    '¿Qué fantasía sexual llevas tiempo queriendo experimentar pero no has tenido el valor de pedirla?',
    '¿Has tenido atracción sexual por alguien de este grupo antes de hoy? ¿Ahora mismo la sigues teniendo?',
    '¿Cuál ha sido tu noche más salvaje e íntima? Descríbela con detalle sin saltarte las partes buenas.',
    '¿Qué frase sucia o cargada de deseo te excita escuchar durante el sexo?',
    '¿Cuál fue tu experiencia sexual más memorable con alguien que acababan de conocerse esa misma noche?',
    '¿Qué es lo que más te cuesta pedir en la cama pero que mueres de ganas que te hagan?',
    '¿Cuál es la zona de tu cuerpo más erógena y cómo te gusta exactamente que te la toquen?',
    '¿Qué es lo más hot o sucio que has dicho o que te han dicho durante el sexo?',
    'Si pudieras elegir a cualquier persona de este grupo para pasar la noche, ¿a quién y qué harías?',
    '¿Has tenido sexo con dos personas al mismo tiempo? Si sí, cuéntalo todo. Si no, ¿lo harías con alguien de aquí?',
    '¿Cuál es el escenario sexual más detallado y hot que has imaginado con alguien de este grupo?',
    '¿Cuál es la cosa más sexual, espontánea e impulsiva que has hecho sin pensarlo dos veces?',
    '¿Cuál es la parte del cuerpo de alguien de este grupo que te ha quitado el sueño?',
    '¿Has tenido fantasías con más de una persona de este grupo al mismo tiempo? ¿Quiénes y qué pasaba?',
    '¿Qué es lo que más te excita visualmente de alguien desnudo/a? ¿En qué es lo primero que te fijas?',
    '¿Cuál es la cosa más atrevida que estás dispuesto/a a hacer esta noche si alguien te lo pide?',
    '¿Cuál fue la primera vez que hiciste algo sexual en grupo o con más de una persona presente? ¿Cómo fue?',
    '¿Has mandado fotos de ti sin ropa a alguien de este grupo o a alguien que ellos conozcan?',
    '¿Qué es lo que te da más vergüenza pedir en la cama pero que en realidad te encantaría que te hicieran?',
    '¿Alguna vez tuviste una fantasía en la que alguien de este grupo era el protagonista? ¿Qué pasaba?',
    '¿Con quién de este grupo te gustaría intercambiar un masaje ahora mismo y qué esperarías que pasara?',
    '¿Qué harías si en este momento alguien de este grupo te tomara de la mano y te llevara a otro cuarto?',
    '¿Cuántas veces al día piensas en sexo y con quién sueles fantasear más seguido?',
    '¿Qué es lo que más te gusta hacer durante el sexo, lo que sientes que se te da increíblemente bien?',
    '¿Alguna vez deseaste que alguien de este grupo te viera de una forma diferente, más íntima? ¿Quién y cuándo?',
    '¿Qué parte de tu cuerpo te gustaría que alguien de este grupo explorara durante 1 minuto sin parar?',
    '¿Cuál es el olor, sonido o sensación que más te enciende durante la intimidad?',
    '¿Qué harías si descubrieras que alguien de este grupo te desea desde hace tiempo?',
    '¿Cuál fue tu experiencia sexual más corta y cuál la más larga? Describe ambas.',
    '¿Cuál es la parte del cuerpo de alguien de este grupo que besarías ahora mismo si el grupo te lo permitiera?',
    '¿Cuál es la cosa más sucia que has buscado o visto en internet que no admitiría normalmente?',
    '¿Alguna vez fantaseaste con alguien de este grupo mientras estabas con otra persona? ¿Quién era?',
    '¿Qué le dirías a alguien de este grupo si pudieras confesar tu deseo más oscuro sin consecuencias?',
    '¿Cuál fue la vez que más disfrutaste haciendo algo que normalmente no haces? ¿Qué fue?',
    '¿Con quién de aquí repetirías una noche sin dudarlo? ¿Qué harías diferente la segunda vez?',
    '¿Qué es lo que más te sorprendió descubrir que te gustaba en la intimidad?',
    '¿Alguna vez le insinuaste algo sexual a alguien de este grupo sin que se diera cuenta? ¿Qué fue?',
    '¿Cuál es la prenda de ropa de alguien de este grupo que más te gustaría quitarle ahora mismo?',
    '¿Si el grupo te dijera que esta noche puedes hacer lo que quieras con una persona de aquí, qué harías?',
    '¿Cuál es el beso más cargado de tensión sexual que has dado o recibido? ¿Con quién fue?',
    '¿Qué harías si alguien de este grupo te enviara un audio de voz muy caliente a las 2 AM?',
    '¿Alguna vez iniciaste el sexo de una forma tan atrevida que la otra persona no lo esperaba? ¿Cómo fue?',
    // --- NUEVAS PREGUNTAS COMPROMETEDORAS Y CALIENTES ---
    '¿Qué es lo que más te excita que alguien te haga en el cuello mientras estás distraído/a?',
    'Si pudieras pasar una noche entera pecando con alguien de esta habitación sin que nadie se entere, ¿a quién elegirías?',
    '¿Cuál es la parte de tu cuerpo que más te gusta que te besen y por qué te vuelve loco/a?',
    '¿Alguna vez has tenido un orgasmo en un lugar público? Cuéntanos dónde y cómo fue el riesgo.',
    '¿Qué prenda de ropa de la persona que tienes enfrente te gustaría quitarle ahora mismo con los dientes?',
    '¿Cuál es el pensamiento más sucio que has tenido sobre alguien de este grupo mientras lo/la mirabas hoy?',
    '¿Has practicado sexting con alguien que esté presente en esta reunión? Si es así, ¿quién?',
    '¿Qué es lo más "prohibido" o fetiche extraño que te gustaría probar pero te da miedo pedir?',
    '¿Cuál es la posición en la que te sientes más dominante y por qué te gusta tener el control?',
    'Si tuviéramos que quedarnos encerrados en una habitación oscura tú y la persona a tu izquierda, ¿qué sería lo primero que le harías?',
    '¿Prefieres que te traten con delicadeza o que sean rudos/as contigo en la intimidad? Sé específico/a.',
    '¿Cuál es el video o contenido para adultos más extraño que has buscado por curiosidad?',
    '¿Qué es lo más atrevido que has hecho bajo las sábanas con alguien que apenas conocías?',
    '¿A quién de este grupo besarías apasionadamente ahora mismo si te dieran 100 dólares?',
    '¿Cuál es tu opinión sobre los tríos? ¿Con qué dos personas de aquí aceptarías intentarlo?',
    '¿Has tenido fantasías con el/la ex de alguno de tus amigos presentes? ¿Quién era?',
    '¿Qué es lo que más te atrae físicamente de la persona a tu derecha, que nunca te atreviste a decirle?',
    '¿Alguna vez has usado comida en tus juegos íntimos? ¿Qué alimento fue y cómo terminó la escena?',
    '¿Cuál es el lugar más "incómodo" donde has sentido una excitación repentina e incontrolable?',
    '¿Qué tan importante es el tamaño para ti? ¿Alguna vez te has llevado una decepción o sorpresa?',
    '¿Has fingido un orgasmo para terminar rápido? ¿Con quién y por qué fue tan aburrido?',
    '¿Qué ruiditos o palabras te gusta decir o escuchar cuando estás en pleno acto?',
    '¿Cuál es la zona de tu cuerpo que consideras tu "botón de encendido" inmediato?',
    '¿Alguna vez has grabado un video íntimo? ¿Aún existe o quién lo tiene?',
    '¿Qué es lo más loco que has hecho por puro deseo sexual y de lo que no te arrepientes?',
    '¿Con quién de aquí tendrías una "relación de solo una noche" sin preguntas ni sentimientos?',
    '¿Cuál es la fantasía que involucra a alguien famoso que más veces has imaginado?',
    '¿Prefieres dar o recibir? Describe tu estilo favorito de juego previo con lujo de detalles.',
    '¿Cuál es el mensaje de texto más caliente que has enviado y a quién fue?',
    '¿Has tenido alguna experiencia con alguien de tu mismo sexo? ¿Te gustaría repetir o probar?',
    '¿Qué es lo primero que le miras a alguien cuando piensas en tener algo íntimo con esa persona?',
    '¿Alguna vez te han pillado masturbándote? ¿Quién fue y cuál fue tu reacción?',
    '¿Qué juguete sexual tienes o te mueres por comprar y usar con alguien?',
    '¿Cuál es la situación más ridícula que te ha pasado en medio de un encuentro sexual?',
    '¿Qué es lo más atrevido que estarías dispuesto/a a hacer frente al grupo si apagáramos las luces?',
    '¿Alguna vez has tenido un sueño húmedo con alguien que esté en esta habitación? ¿Qué pasaba en el sueño?',
    '¿Cuál es tu técnica infalible para seducir a alguien que te gusta mucho?',
    '¿Qué opinas del sexo anal? ¿Es un sí, un no o un "quizás con la persona correcta"?',
    '¿Cuál es el secreto más caliente que guardas de una relación pasada?',
    '¿Si pudieras lamer cualquier parte del cuerpo de la persona a tu izquierda, cuál elegirías?',
  ],

  retos: [
    'Dale un beso en los labios a quien elija el grupo — mínimo 5 segundos, sin prisa y sin reírte.',
    'La persona que el grupo elija puede hacerte lo que quiera durante 30 segundos — sin zonas íntimas. No puedes apartarlos.',
    'Siéntate en el regazo de alguien que elija el grupo durante 2 minutos completos. No te puedes mover.',
    'Dale un masaje en la espalda completa a alguien del grupo durante 3 minutos. El grupo decide si va bajo la ropa.',
    'Acércate a alguien del grupo, ponle la mano en el cuello y susúrrale al oído lo más explícito que se te ocurra.',
    'Deja que alguien del grupo te dé un masaje en espalda, cuello y hombros por 3 minutos. No puedes moverte.',
    'Baila pegado/a de forma muy sugestiva con quien elija el grupo durante 2 minutos. Con contacto real y sin reírte.',
    'Dale a alguien del grupo un abrazo de 2 minutos sin soltarte. El grupo decide si va por delante o por detrás.',
    'Coquetea con alguien usando solo miradas, respiración y lenguaje corporal durante 2 minutos sin hablar.',
    'Deja que alguien te acaricie el cabello y el cuello por 2 minutos mientras te mira fijamente a los ojos.',
    'Haz un strip tease de 1 minuto completo con música y movimientos. Sin quitarte nada, pero con toda la intención.',
    'Susúrrale al oído a alguien del grupo exactamente lo que le harías si estuvieran solos esta noche.',
    'Mantén contacto visual cargado de tensión sexual con alguien del grupo durante 2 minutos sin hablar.',
    'Di en voz alta y con detalle las 3 cosas físicas que más te atraen de alguien del grupo que el grupo elija.',
    'El grupo vota a dónde recibes un beso esta vez: labios, cuello o escote. Sin negarte.',
    'El grupo vota qué prenda o accesorio te quitas. Se queda afuera hasta el final del juego.',
    'Di qué zona de tu cuerpo más disfrutas que te toquen y deja que alguien lo haga exactamente así 20 segundos.',
    'Te vendan los ojos. Dos personas te tocan el cuello y los hombros. Adivina quién es quién.',
    'Describe con detalle lo que harías con alguien del grupo si tuvieran la noche entera solos.',
    'El grupo decide si le das un beso en los labios a alguien — mínimo 8 segundos, con calma.',
    'Seduce a alguien del grupo durante 90 segundos usando voz, mirada y contacto. Sin reírte.',
    'Describe tu fantasía sexual más recurrente con todos los detalles. El grupo puede hacer preguntas.',
    'El grupo elige a alguien. Le pones la mano en la cara y la miras a los ojos durante 1 minuto en silencio.',
    'El grupo elige dos personas. Se sientan frente a frente y mantienen tensión visual durante 2 minutos sin romperla.',
    'Deja que el grupo elija a alguien para que te dé un masaje de 2 minutos donde esa persona quiera.',
    'El grupo elige a alguien. Le das un masaje en cabeza y cuello durante 2 minutos con los ojos cerrados.',
    'Recuéstate en el regazo de alguien del grupo durante 2 minutos. Esa persona decide si te acaricia.',
    'Di el nombre de la persona de este grupo con quien compartirías cama esta noche y por qué exactamente.',
    'El grupo decide que alguien te dé un beso en el cuello — esa persona decide la duración.',
    'Actúa cómo le quitarías la ropa a alguien de este grupo pieza por pieza — con mímica y sin prisa.',
    'Alguien del grupo te susurra algo muy explícito al oído. Tienes que repetirlo en voz alta al resto.',
    'Di en voz alta tu fantasía más recurrente con alguien de este grupo — nombre incluido.',
    'El grupo elige quién te da un masaje en la espalda directamente sobre la piel durante 2 minutos.',
    'Describe cómo sería exactamente una noche perfecta con alguien de este grupo — desde que empieza.',
    'El grupo vota quién te abraza por detrás durante 1 minuto. Esa persona puede hacer lo que quiera con las manos.',
    'Cuéntale al grupo tu experiencia sexual más hot con absolutamente todos los detalles. El grupo puede preguntar.',
    'El grupo elige una zona de tu cuerpo. Alguien te toca ahí como quiera durante 20 segundos.',
    'Actúa cómo seduces a alguien en una fiesta — voz, cuerpo, mirada — con alguien del grupo como objetivo.',
    'Di las 5 cosas que más te gustan que te hagan en la cama, en orden de mayor a menor, con detalle.',
    'El grupo te ata las manos con algo durante 3 minutos. Alguien decide qué hacerte durante ese tiempo.',
    'Recrea tu beso más apasionado: descríbelo con todos los detalles y luego actúalo con alguien del grupo.',
    'El grupo elige quién te da un beso en el cuello o el escote — lento y sin prisa.',
    'Di en voz alta todo lo que le harías a alguien del grupo si tuvieran la noche libre y sin consecuencias.',
    'El grupo te cubre los ojos. Dos personas te recorren espalda y cuello con las manos. Adivina quién es quién.',
    'El grupo elige a alguien. Le acaricias la espalda bajo la ropa durante 1 minuto sin parar.',
    'Susúrrale a alguien del grupo tu fantasía más reciente con esa persona — solo esa persona escucha.',
    'Baila encima de alguien del grupo durante 1 minuto. El grupo pone la canción.',
    'Dale un beso en el cuello a alguien del grupo durante 15 segundos sin levantar los labios.',
    'Di en voz alta lo que pensarías si alguien de este grupo entrara sin ropa a tu cuarto esta noche.',
    'El grupo elige a alguien. Le quitas una prenda despacio y sin prisa.',
    'Deja que alguien del grupo te recorra el cuello con los labios — rozando apenas — durante 20 segundos.',
    'El grupo elige a alguien. Le dices al oído la parte de su cuerpo que más te gusta y por qué.',
    'Actúa cómo reaccionarías si alguien te despertara en medio de la noche con intenciones muy claras.',
    'El grupo elige pareja y se dan un abrazo de 3 minutos cuerpo a cuerpo sin separarse.',
    'Di cuál es la parte de tu cuerpo que mejor se te da usar en la intimidad y demuéstralo con mímica.',
    'Deja que alguien del grupo te levante la camiseta y te acaricie el estómago durante 20 segundos.',
    'El grupo elige dos personas. Una le dice a la otra exactamente qué haría con esa persona si estuvieran solos.',
    'Actúa cómo seduces a alguien usando solo movimientos de cadera y contacto visual durante 1 minuto.',
    'El grupo elige a alguien. Le das un beso en cada parte del cuello durante 30 segundos sin parar.',
    'Intercambia una prenda de ropa con alguien que elija el grupo. Póntela y quédate así el resto del juego.',
    'El grupo elige a alguien. Le acaricias el cabello, la cara y el cuello durante 2 minutos sin hablar.',
    'Deja que alguien del grupo te quite los zapatos y calcetines y te acaricie los pies durante 1 minuto.',
    'El grupo elige a alguien. Le das un beso en el hombro, en el cuello y en la oreja en ese orden y sin prisa.',
    'El grupo elige dos personas. Una le explica a la otra sus tres cosas favoritas en la intimidad, con detalle.',
    'Deja que alguien del grupo decida la posición exacta en que te tienes que quedar durante 2 minutos.',
    'El grupo elige a alguien. Le das un masaje en los pies durante 2 minutos mientras esa persona puede hablar o no.',
    'Di en voz alta qué harías si alguien de este grupo te enviara un mensaje a la 1 AM diciendo solo "¿estás?"',
    'Actúa como si estuvieras viendo algo muy hot — reacciones incluidas — durante 30 segundos. Sin vergüenza.',
    'Deja que el grupo decida en qué parte de tu cuerpo alguien te dibuja con su dedo durante 1 minuto.',
    'El grupo elige a alguien. Sin hablar, le transmites con mirada y cuerpo que lo/la deseas durante 1 minuto.',
    'Deja que alguien te cubra los ojos y te dé un beso en alguna parte del cuerpo sin decirte dónde va a ser.',
    'El grupo elige a alguien. Le cuentas al oído la última vez que pensaste en esa persona de forma íntima.',
    'Actúa cómo le propondrías a alguien de este grupo algo sin decir ni una palabra — solo con el cuerpo.',
    'El grupo elige dos personas. Se dan un beso de al menos 10 segundos frente a todos sin apresurarse.',
    'Deja que el grupo decida que alguien te acaricie desde el hombro hasta la mano durante 1 minuto completo.',
    'Di en voz alta cuál es el momento en que más has deseado a alguien de este grupo y qué querías hacer.',
    'El grupo elige a alguien. Le demuestras con mímica exacta cómo te gustaría que te tocara sin decir nada.',
    'Recréa con alguien del grupo la escena de apertura de una película romántica para adultos que el grupo elija.',
    'Deja que alguien del grupo te revise los bolsillos o la ropa buscando "algo" durante 30 segundos.',
    'El grupo elige a alguien. Le haces cosquillas en la zona que el grupo decida durante 30 segundos.',
    'Deja que alguien del grupo te siente en sus piernas y te tenga así durante 2 minutos completos.',
    // --- NUEVOS RETOS DIRECTOS (PARA RULETA O JUEGO ADULTO) ---
    
    // NIVEL: TENSIÓN FÍSICA
    'Cierra los ojos y deja que la persona a tu derecha recorra tu clavícula y cuello con sus labios, sin llegar a besar.',
    'Elige a alguien para que te susurre al oído, con voz muy ronca, tres cosas que te haría si la habitación se quedara a oscuras.',
    'Deja que la persona de enfrente use una prenda para vendarte los ojos y te toque donde ella quiera durante un minuto entero.',
    'Siéntate frente a la persona a tu izquierda con las frentes pegadas y deja que te acaricie las manos mientras te mira fijamente.',
    'Recibe un beso "frío" en el lugar más sensible que tú elijas por parte de la persona a tu derecha, usando un cubo de hielo.',
    'Permite que la persona de enfrente te sople aire caliente en el oído y luego te dé un mordisco suave en el lóbulo.',
    'Elige a alguien para que deslice su mano por debajo de tu ropa hasta tocar piel y la deje ahí durante toda la siguiente ronda.',
    'Sostiene un vaso con tus dientes mientras la persona a tu izquierda bebe de él sin usar las manos, mirándote a los ojos.',
    'Deja que la persona a tu derecha verifique el color de tu ropa interior y lo anuncie en voz alta al grupo.',
    'Recibe un beso de 15 segundos en la cara interna de tu muñeca o del codo por parte de la persona de enfrente.',
    'Deja que la persona a tu izquierda te quite los calcetines usando solo sus dientes y luego te dé un beso en el pie.',
    'Permite que la persona a tu derecha pase su lengua por tu oreja de abajo hacia arriba y luego te diga una palabra sucia.',
    'Deja que la persona a tu izquierda te desabroche el cinturón o el primer botón del pantalón usando solo una mano.',
    'Intercambia una prenda de ropa interior con alguien (si se atreven) o una prenda visible por el resto del juego.',
    'Recibe un beso "esquinado" en la comisura de tus labios de la persona de enfrente, que dure hasta que el grupo diga basta.',
    'Deja que la persona a tu izquierda te recorra la columna vertebral con un dedo, presionando suavemente, desde la nuca hasta la cintura.',
    'Permite que la persona a tu derecha te muerda suavemente el hombro y deje su marca frente a todos.',
    'Deja que la persona de enfrente se tome un "body shot" de tu cuerpo; tú eliges la zona (excepto íntimas).',
    'Deja que la persona a tu izquierda te lama un dedo y luego lo use para recorrerte los labios lentamente.',
    'Haz un "beso francés" con la persona de enfrente, pero sin usar las manos, solo el contacto de las bocas.',
    'Permite que la persona a tu derecha te quite la camisa o blusa y te dé un masaje con aceite en la espalda por 2 minutos.',
    'Recibe un hielo de la boca de la persona de enfrente sin usar las manos; si se cae, quítate otra prenda.',
    'Permite que la persona a tu derecha te meta un hielo por la espalda y no puedes moverte hasta que se derrita.',
    'Deja que la persona de enfrente te dé un beso en el cuello e intente dejarte una marca (chupetón).',

    // NIVEL: EXTREMO / LAVA
    'Deja que la persona a tu izquierda te quite una prenda de ropa usando solo sus dientes mientras mantienes las manos en la nuca.',
    'Permite que dos personas del grupo te acaricien al mismo tiempo en zonas diferentes por 1 minuto con los ojos cerrados.',
    'Deja que la persona a tu derecha te vende los ojos y pase un objeto o parte de su cuerpo por tus labios; adivina qué es.',
    'Permite que la persona de enfrente te use como "mesa" para comer un dulce directamente de tu abdomen o clavícula.',
    'Deja que la persona a tu derecha te desabroche una prenda y meta su mano para acariciarte la piel por 2 minutos seguidos.',
    'Recibe un "lap dance" de 1 minuto por parte de la persona que el grupo considere que más te atrae.',
    'Deja que la persona a tu derecha te dé un beso apasionado de 30 segundos mientras el resto cronometra.',
    'Deja que la persona de enfrente te baje un poco el pantalón o suba la falda y se quede mirándote fijamente por 20 segundos.',
    'Permite que alguien del grupo te lama la zona del cuerpo que ellos elijan por sorteo (excepto zonas íntimas).',
    'Deja que la persona a tu derecha te meta un cubo de hielo en la ropa interior; aguanta 1 minuto sin sacarlo.',
    'Recibe un beso francés de la persona a tu izquierda mientras la persona a tu derecha te acaricia el cabello sugerentemente.',
    'Deja que la persona de enfrente te muerda el labio superior y la persona a tu izquierda el inferior al mismo tiempo por 5 segundos.',
    'Elegir a alguien para que te dé nalgadas rítmicas mientras tú tienes que decir el nombre de esa persona en tono sugerente.',
    'Deja que alguien del grupo te explore por dentro de la ropa con un objeto frío por 30 segundos.',
    'Deja que la persona a tu derecha te desabroche el sujetador (si usas) o te suba la camiseta y te dé un beso en cada pecho.',
    'Permitir que la persona a tu derecha te ponga en la posición que ella quiera y te susurre: "eres mío/a" al oído.',
    'Permitir que la persona a tu derecha te unte algo comestible en los labios y lo limpie usando solo su lengua.',
    'Recibe un beso apasionado de la persona de enfrente mientras el grupo les echa un poco de agua fría encima.',
    'Permitir que la persona a tu izquierda te meta la mano por detrás del pantalón y te dé un apretón suave.',
    'Lame un cubo de hielo de la piel de la persona a tu izquierda en la zona que ella elija.',
    'Mantente a un milímetro de los labios de la persona de enfrente por 1 minuto; el primero que bese o se aparte pierde.',
    'Deja que la persona a tu derecha te dé un masaje en los muslos subiendo lo más posible sin tocar zona íntima.',
    'Recibe un beso francés con los ojos vendados y trata de adivinar quién del grupo te lo dio.',
    'Desabrocha el cinturón o pantalón de la persona de enfrente usando solo tus dientes.',
    'Deja que dos personas beban un "body shot" de tu abdomen al mismo tiempo.',
    'Permite que la persona a tu izquierda te explore con la lengua el cuello y la oreja durante 30 segundos.',
    'Recibe un beso apasionado mientras la persona de enfrente te mantiene contra la pared con ambas manos.',
    'Lame el cuello de la persona a tu derecha de abajo hacia arriba hasta llegar a sus labios muy lento.',
    'Recibe un beso húmedo y largo directamente en el ombligo por parte de la persona que elijas.',
    'Recibe una nalgada marcada con la mano desnuda por parte de la persona de enfrente.',
    'Quítale una prenda de ropa a la persona a tu izquierda usando solo una mano.',
    'Lame una línea de dulce o alcohol de tu clavícula y deja que la persona a tu derecha lo limpie con su lengua.',
    'Recibe un beso en "estéreo": dos personas te besan el cuello o las mejillas al mismo tiempo por 20 segundos.',
    'Deja que alguien acerque su boca a tu entrepierna y respire caliente sobre la ropa por 15 segundos sin tocar.',
    'Deja que la persona a tu derecha te "marque" con un mordisco suave o un beso de labial en el hombro.',
    'Recibe un masaje firme en los glúteos por encima de la ropa por parte de la persona a tu izquierda.',
    'Quítate la ropa interior sin quitarte el pantalón o falda frente a todos (puedes cubrirte con una manta).',
    'Recibe un beso francés que dure lo mismo que tarda en derretirse un hielo pequeño en tu mano.',
    'Deja que la persona de enfrente te levante la prenda superior y te dé un beso en el abdomen.',
    'Lame el lóbulo de la persona a tu izquierda mientras le rodeas la cintura con tus piernas.',
    'Recibe un beso en el punto más sensible de tu cuerpo (no íntimo) elegido por ti.',
    'Véndate los ojos; tres personas te tocarán y debes elegir a una para darle un beso apasionado.',
    'Deja que alguien te meta la mano por detrás del pantalón y te dé un apretón firme.',
    'Siéntate a horcajadas sobre la persona de enfrente y rocen sus narices hasta que uno no aguante y bese.',
    'Deja que la persona a tu izquierda recorra tu ombligo con la lengua y suba hasta tus pechos (sobre la ropa).',
    'Quítale una prenda a la persona a tu derecha usando solo tus pies.',
    'Baila un "lento" muy pegado con la persona de enfrente, manteniendo contacto total de los cuerpos.',
    'Recibe besos húmedos en las rodillas y deja que la persona suba besando por tus piernas hasta que digas basta.',
    'Deja que la persona a tu derecha te muerda el labio inferior y no te suelte por 10 segundos.',
    'Deja que alguien te acaricie el cuello mientras confiesas tu fantasía más oscura con esa persona.',
    // --- RETOS ADULTO: CONTROL Y CONTACTO (LAVA PURA) ---
    'Cierra los ojos y deja que la persona a tu izquierda haga lo que quiera contigo durante 1 minuto (si algo no te gusta, lo paras).',
    'Quédate en ropa interior durante las próximas 3 rondas del juego.',
    'Deja que la persona de enfrente elija una zona de tu cuerpo para darte un beso húmedo y lento.',
    'Permite que la persona a tu derecha te desabroche el pantalón o suba tu falda y meta su mano por 30 segundos.',
    'Véndate los ojos y deja que alguien del grupo pase su lengua por donde quiera; tienes que adivinar quién fue.',
    'Deja que la persona a tu izquierda te quite una prenda de ropa usando solo sus dientes.',
    'Permite que la persona de enfrente te dé un "body shot" (beber alcohol de tu cuerpo) desde tu ombligo o pecho.',
    'Ponte de rodillas frente a la persona a tu derecha y deja que te agarre del cabello mientras te mira fijamente.',
    'Deja que la persona a tu izquierda te recorra la columna vertebral con su lengua, desde la nuca hasta donde empieza el pantalón.',
    'Permite que alguien del grupo te dé 5 nalgadas fuertes con la mano desnuda.',
    'Deja que la persona de enfrente te meta un hielo en la boca y luego te dé un beso francés hasta que el hielo se derrita.',
    'Quítate la camisa y deja que la persona a tu derecha te dé un masaje con sus labios por toda tu espalda.',
    'Deja que la persona a tu izquierda te muerda el labio inferior y tire de él con fuerza controlada por 10 segundos.',
    'Permite que la persona de enfrente te explore por debajo de la ropa interior con un solo dedo durante 20 segundos.',
    'Siéntate a horcajadas (encima) de la persona a tu derecha y rocen sus cuerpos rítmicamente por 1 minuto.',
    'Deja que el grupo elija a alguien para que te dé un beso apasionado en la zona que tú consideres más erógena.',
    'Permite que la persona a tu izquierda te susurre sus fantasías más oscuras mientras te lame el lóbulo de la oreja.',
    'Deja que alguien te desabroche el sujetador (si usas) o te baje el bóxer un poco y te dé un beso en la zona descubierta.',
    'Quédate inmóvil y deja que la persona de enfrente te use como "mesa" para lamer algo dulce de tu abdomen.',
    'Deja que la persona a tu derecha te dé un beso francés "sorpresa" en cualquier momento de los próximos 5 minutos.',
    'Permite que alguien te dé un beso en la cara interna del muslo, lo más cerca posible de la entrepierna.',
    'Deja que la persona a tu izquierda te meta la mano por detrás del pantalón y te dé un apretón firme en los glúteos.',
    'Cierra los ojos y deja que la persona de enfrente te dé un beso en los labios; si te gusta, debes usar la lengua para pedir más.',
    'Deja que alguien del grupo te quite los calcetines con los dientes y te lama la planta del pie.',
    'Permite que la persona a tu derecha te dé un mordisco en el cuello lo suficientemente fuerte como para dejar marca.',
    'Deja que la persona de enfrente te desabroche la camisa por completo y te dé un beso en cada pezón.',
    'Ponte en posición de gateo y deja que la persona a tu izquierda te dé una nalgada y te diga algo sucio.',
    'Deja que alguien del grupo use su boca para recorrer tu cuello de arriba abajo hasta llegar a tu pecho.',
    'Permite que la persona a tu derecha te agarre por la cintura y te pegue a su cuerpo sintiendo todo su contacto físico.',
    'Deja que la persona de enfrente te dé un beso húmedo en el ombligo y luego baje besando hasta el borde de tu ropa.',
    'Permite que la persona a tu izquierda te introduzca un dedo en la boca mientras tú lo succionas mirándola a los ojos.',
    'Deja que el grupo elija a una pareja para que te den un "sándwich" de caricias por debajo de tu ropa.',
    'Permite que alguien te unte un poco de bebida en los labios y la limpie con un beso francés profundo.',
    'Deja que la persona a tu derecha te quite una prenda y la use ella por el resto del juego.',
    'Permite que la persona de enfrente te dé un beso en la nuca y luego baje sus manos hasta tus partes íntimas (por fuera).',
    'Deja que alguien te susurre palabras obscenas al oído mientras te muerde el cuello.',
    'Permite que la persona a tu izquierda te dé un masaje en los muslos con aceite o crema, subiendo lo más que pueda.',
    'Quédate en silencio mientras la persona de enfrente te describe detalladamente qué te haría en la cama ahora mismo.',
    'Deja que la persona a tu derecha te dé un beso "esquinado" y luego lama tu labio superior muy lento.',
    'Permite que alguien te dé un beso en la base de la espalda y luego te dé una nalgada de despedida.',
    // --- TANDA EXTREMA: CONTACTO Y CESIÓN DE CONTROL (NIVEL LAVA) ---
    'Quítate una prenda de ropa y deja que la persona a tu izquierda elija dónde ponértela de nuevo (o si te quedas sin ella).',
    'Cierra los ojos y deja que la persona de enfrente te explore con sus manos por 1 minuto; tú solo puedes disfrutar.',
    'Deja que la persona a tu derecha te dé un beso francés y, a mitad del beso, que el grupo decida si deben seguir 30 segundos más.',
    'Permite que alguien del grupo te desabroche el pantalón y te dé un beso en la zona de la pelvis (por encima o por debajo de la ropa interior).',
    'Quédate en ropa interior y deja que la persona a tu izquierda te unte un poco de bebida en el pecho y la limpie con su lengua.',
    'Véndate los ojos y deja que la persona de enfrente te coloque en la posición sexual que ella quiera por 30 segundos (solo la pose).',
    'Deja que la persona a tu derecha te meta la mano por debajo de la camiseta y te acaricie los pezones hasta que el grupo diga basta.',
    'Permite que alguien te dé un beso húmedo en el interior del muslo, subiendo lo más que pueda sin tocar la zona íntima.',
    'Deja que la persona a tu izquierda te muerda el labio superior mientras la de la derecha te besa el cuello al mismo tiempo.',
    'Quítate los zapatos y deja que la persona de enfrente te lama un dedo del pie de forma sugerente.',
    'Deja que la persona a tu derecha te baje la ropa interior un poco por detrás y te dé una nalgada directamente en la piel.',
    'Permite que alguien del grupo te introduzca un dedo en la boca y tú debes succionarlo como si fuera algo más.',
    'Deja que la persona a tu izquierda te desabroche el sujetador (si usas) y se quede mirando tus pechos por 15 segundos.',
    'Ponte frente a la persona de enfrente y deja que te recorra todo el cuerpo con un hielo, desde el cuello hasta los tobillos, por dentro de tu ropa.',
    'Deja que la persona a tu derecha te dé un beso en el ombligo y baje con la lengua hasta donde tú decidas parar.',
    'Permite que alguien te agarre fuertemente del cabello y te dé un beso apasionado contra la pared.',
    'Deja que la persona a tu izquierda meta su mano en tu ropa interior y te dé un apretón suave por 10 segundos.',
    'Quédate inmóvil y deja que la persona de enfrente te dé besos por todo el torso desnudo durante un minuto.',
    'Deja que el grupo elija a una pareja para que te hagan un "sandwich" de cuerpos, apretándote entre ellos sin ropa superior.',
    'Permite que la persona a tu derecha te dé un "body shot" directamente desde tu pecho o abdomen.',
    'Deja que la persona de enfrente te susurre sus fantasías más sucias contigo mientras te muerde la oreja con fuerza.',
    'Quítate una prenda y deja que la persona a tu izquierda decida quién del grupo debe quitártela usando solo los dientes.',
    'Deja que alguien te unte algo dulce en el cuello y lo limpie con besos lentos y profundos.',
    'Permite que la persona a tu derecha te explore la entrepierna por encima del pantalón/falda con movimientos circulares por 1 minuto.',
    'Deja que la persona de enfrente te dé un beso francés mientras te acaricia los glúteos con ambas manos.',
    'Quédate en ropa interior y deja que el grupo decida quién te dará un masaje con aceite en todo el cuerpo.',
    'Deja que la persona a tu izquierda te muerda el cuello y te deje una marca visible frente a todos.',
    'Permite que alguien te baje la cremallera del pantalón y meta su mano para acariciarte por 30 segundos.',
    'Deja que la persona de enfrente se siente sobre tus piernas y te dé un beso apasionado mientras te abraza fuerte.',
    'Permite que la persona a tu derecha te dé un beso en cada pezón (por debajo de la ropa si prefieres).',
    'Deja que alguien del grupo te pase la lengua por la nuca y luego te sople aire caliente.',
    'Permite que la persona a tu izquierda te quite la ropa interior (si te atreves) y la lance al centro del círculo.',
    'Deja que la persona de enfrente te dé un beso en la base de la columna y suba besando cada vértebra hasta la nuca.',
    'Permite que alguien te dé una nalgada y luego te meta un hielo en el pantalón por 30 segundos.',
    'Deja que la persona a tu derecha te agarre por la cintura y te pegue a ella mientras te besa el cuello de forma salvaje.',
    'Quédate en silencio y deja que la persona de enfrente te toque como ella quiera durante 1 minuto (tienes el poder de parar si quieres).',
    'Deja que alguien te lama el lóbulo de la oreja mientras otra persona te acaricia los muslos.',
    'Permite que la persona a tu izquierda te dé un beso "negro" (en la comisura) y luego use su lengua para entrar en tu boca.',
    'Deja que la persona de enfrente te desabroche la camisa y te pase un objeto frío por todo el pecho.',
    'Permite que alguien del grupo te dé un beso francés de despedida al final de esta ronda, que dure al menos 20 segundos.',
    // --- TANDA INFIERNO: CONTACTO DIRECTO Y TENSIÓN MÁXIMA ---
    'Deja que la persona a tu izquierda te quite una prenda de ropa usando solo sus manos, pero tú debes tener los ojos vendados.',
    'Permite que la persona de enfrente te dé un beso francés "con mordisco" incluido, hasta que alguien del grupo diga "ya".',
    'Quédate en ropa interior y deja que la persona a tu derecha te dibuje algo en el abdomen usando únicamente su lengua.',
    'Deja que alguien del grupo te desabroche el pantalón y deslice su mano por tu ropa interior durante 40 segundos.',
    'Permite que la persona a tu izquierda te dé un beso en la zona más sensible que tengas (tú eliges), pero debe ser un beso muy húmedo.',
    'Deja que la persona de enfrente te agarre del cuello con una mano mientras te da un beso apasionado contra la pared.',
    'Quédate solo en ropa interior y deja que dos personas del grupo te den un masaje con aceite en los muslos y la espalda al mismo tiempo.',
    'Deja que la persona a tu derecha te quite el sujetador (si usas) o la camiseta y te dé un beso en cada pezón por 10 segundos.',
    'Permite que alguien te baje la ropa interior lo suficiente para darte un beso en el glúteo y luego una nalgada fuerte.',
    'Deja que la persona de enfrente te meta un dedo en la boca mientras tú debes succionarlo mirándola fijamente a los ojos.',
    'Permite que la persona a tu izquierda te explore la entrepierna por debajo de la ropa por 30 segundos (tú decides el límite).',
    'Deja que la persona a tu derecha te dé un beso en el cuello y vaya bajando con la lengua hasta llegar a tu zona íntima (por encima de la ropa).',
    'Ponte en posición de gateo y deja que la persona de enfrente se suba encima de ti y te dé 3 nalgadas marcadas.',
    'Deja que alguien te unte un hielo en los labios y luego te dé un beso francés profundo para pasarte el frío.',
    'Permite que la persona a tu izquierda te desabroche la camisa y te lama desde el ombligo hasta la garganta en una línea recta.',
    'Deja que la persona de enfrente te susurre al oído lo que te haría en la cama mientras te muerde el lóbulo con fuerza.',
    'Permite que alguien del grupo te quite una prenda de ropa usando solo sus dientes y la tire lejos.',
    'Deja que la persona a tu derecha te dé un "body shot" desde tu zona pélvica (por encima de la ropa).',
    'Quédate en ropa interior y deja que la persona a tu izquierda te dé un beso en la cara interna de ambos muslos.',
    'Deja que la persona de enfrente te agarre de las manos por encima de tu cabeza mientras te besa el cuello salvajemente.',
    'Permite que alguien te introduzca un hielo en la ropa interior y la persona a tu derecha debe sacarlo usando solo su boca.',
    'Deja que la persona a tu izquierda te desabroche el primer botón del pantalón y meta su mano para "saludarte" por 20 segundos.',
    'Permite que la persona de enfrente te dé un beso francés mientras te aprieta los glúteos con ambas manos.',
    'Deja que alguien te dé un beso en el ombligo y luego use su lengua para juguetear ahí dentro por 15 segundos.',
    'Quédate en ropa interior y deja que el grupo elija a alguien para que te dé un beso en el pecho y te deje una marca.',
    'Deja que la persona a tu derecha te meta la mano por detrás del pantalón y te acaricie la piel desnuda de los glúteos.',
    'Permite que la persona de enfrente te dé un beso en los labios y luego baje besando tu cuerpo hasta tus rodillas.',
    'Deja que alguien te agarre por la cintura por detrás y te pegue a su cuerpo mientras te muerde el hombro.',
    'Permite que la persona a tu izquierda te desabroche una prenda y te dé un beso en la piel recién descubierta.',
    'Deja que la persona de enfrente te diga una palabra sucia al oído y luego te dé un beso con mucha lengua.',
    'Quédate solo en ropa interior y deja que la persona a tu derecha te recorra el cuerpo con sus labios sin llegar a besar.',
    'Deja que alguien del grupo te dé una nalgada tan fuerte que deje la marca de su mano en tu piel.',
    'Permite que la persona a tu izquierda te dé un beso francés mientras tú le acaricias la entrepierna (por encima de la ropa).',
    'Deja que la persona de enfrente te baje un poco el bóxer o la braga y te dé un beso en la cadera.',
    'Permite que alguien te lama el cuello desde la base hasta la oreja y luego te dé un soplido caliente.',
    'Deja que la persona a tu derecha te ponga en la posición que ella quiera y te dé un beso apasionado de 20 segundos.',
    'Permite que la persona de enfrente te desabroche la camisa y use su lengua para recorrer tus pezones.',
    'Deja que alguien del grupo te meta un hielo en la boca y te dé un beso francés; el hielo debe pasar de boca a boca.',
    'Quédate en silencio mientras la persona a tu izquierda te toca por debajo de la ropa (tú pones el límite de tiempo).',
    'Deja que la persona de enfrente te dé un beso francés de despedida de esta ronda, usando mucha, mucha lengua.',
    // --- TANDA ELITE: ROZAMIENTOS Y CONTACTO DIRECTO (NIVEL LAVA) ---
    'Siéntate a horcajadas sobre la persona a tu derecha y rebota suavemente mientras el grupo cuenta hasta 30.',
    'Deja que la persona a tu izquierda se siente en tus piernas y se mueva al ritmo de una canción lenta por 1 minuto.',
    'Ponte de espaldas a la persona de enfrente y deja que pegue su cuerpo al tuyo y te dé una nalgada que se escuche en toda la sala.',
    'Permite que la persona a tu derecha te desabroche el pantalón y use su boca para darte un beso en el borde de tu ropa interior.',
    'Deja que alguien del grupo te levante la camiseta y pase su lengua por tus pezones de forma circular.',
    'Véndate los ojos y deja que la persona a tu izquierda te toque "donde ella quiera" durante 1 minuto (tú decides si sigues o paras).',
    'Permite que la persona de enfrente te dé un beso francés mientras te aprieta los muslos y te acerca más a ella.',
    'Siéntate en el regazo de la persona a tu derecha y deja que te dé un mordisco en el cuello mientras tú gimes su nombre.',
    'Deja que la persona a tu izquierda meta su mano en tu ropa interior por detrás y te acaricie con fuerza por 20 segundos.',
    'Permite que alguien te unte un poco de alcohol o dulce en la entrepierna (sobre la ropa) y lo limpie con su lengua.',
    'Quédate en ropa interior y deja que la persona de enfrente te dé un masaje en los glúteos con ambas manos desnudas.',
    'Deja que la persona a tu derecha te agarre del cuello y te dé un beso apasionado mientras tú rodeas su cintura con tus piernas.',
    'Permite que la persona a tu izquierda te desabroche el sujetador (si usas) o te baje el bóxer y te dé un beso en la zona descubierta.',
    'Ponte frente a la persona de enfrente y rocen sus zonas íntimas (con ropa) rítmicamente durante 30 segundos.',
    'Deja que alguien del grupo te lama el cuello desde la clavícula hasta la oreja y termine con un mordisco fuerte.',
    'Permite que la persona a tu derecha te meta un dedo en la boca y te dé una nalgada cada vez que tú lo succiones.',
    'Quédate solo en ropa interior y deja que la persona de enfrente te use como "mesa" para comer algo de tu pecho.',
    'Deja que la persona a tu izquierda te explore por debajo de la ropa con un objeto frío (como una botella) por 1 minuto.',
    'Permite que alguien te dé un beso francés profundo mientras otra persona te acaricia los glúteos por fuera.',
    'Siéntate en las piernas de la persona a tu derecha y deja que te susurre al oído qué posición sexual le gustaría probar contigo hoy.',
    'Deja que la persona de enfrente te baje un poco la ropa interior por delante y te dé un beso muy lento ahí abajo.',
    'Permite que la persona a tu izquierda te dé un masaje en la cara interna del muslo con su lengua.',
    'Deja que alguien del grupo te dé 5 nalgadas seguidas y tú tienes que pedir "más" después de cada una.',
    'Permite que la persona a tu derecha te desabroche la camisa y te dé un beso húmedo en el ombligo que baje más.',
    'Quédate en silencio mientras la persona de enfrente te describe qué siente al tocar tu piel ahora mismo.',
    'Deja que la persona a tu izquierda te muerda el labio inferior y no te suelte hasta que tú la beses con lengua.',
    'Permite que alguien te agarre por la cintura y te pegue a la pared mientras te besa el pecho (sobre la ropa).',
    'Deja que la persona a tu derecha te meta la mano por el pantalón y te dé un apretón firme en los genitales (con cuidado).',
    'Siéntate encima de la persona de enfrente, cara a cara, y muévanse como si estuvieran haciendo el amor (con ropa).',
    'Deja que la persona a tu izquierda te dé un beso en la nuca y luego te baje el cierre o botón de tu prenda inferior.',
    'Permite que alguien te dé un beso francés mientras te muerde suavemente la lengua.',
    'Deja que la persona de enfrente te recorra el cuerpo con un hielo por dentro de tu ropa interior.',
    'Permite que la persona a tu derecha te dé una nalgada y luego te meta la mano por debajo de la blusa/camisa.',
    'Deja que alguien te lama el pezón (sobre la ropa o piel) hasta que esté lo suficientemente excitado/a.',
    'Siéntate en las piernas de la persona a tu izquierda y dejen que sus labios se rocen sin llegar a besarse por 1 minuto.',
    'Deja que la persona de enfrente te desabroche el cinturón usando solo sus dientes.',
    'Permite que alguien te dé un beso en la base de la espalda y baje sus manos hasta tu entrepierna por 15 segundos.',
    'Deja que la persona a tu izquierda te dé un beso francés mientras tú le quitas una prenda de ropa.',
    'Quédate solo en ropa interior y deja que el grupo decida quién te dará un beso en el lugar más "prohibido".',
    'Deja que la persona de enfrente te dé una nalgada fuerte y luego te dé un beso apasionado de 10 segundos.',
  ],
};