window.PREGUNTAS_SUAVE = {
  verdades: [
    '¿Cuál es tu mayor miedo que nunca le has contado a nadie?',
    '¿Cuál fue tu crush más vergonzoso de la infancia?',
    '¿Qué es lo más raro que has comido por accidente?',
    '¿Alguna vez fingiste estar enfermo/a para no ir a algún lugar?',
    '¿Cuál es tu peor hábito que intentas esconder?',
    '¿A quién en este grupo llamarías si estuvieras en problemas a las 3 AM?',
    '¿Cuál es tu película favorita que te da vergüenza admitir?',
    '¿Alguna vez lloraste con una película infantil? ¿Cuál?',
    '¿Qué canción pones cuando estás completamente solo/a?',
    '¿Cuál es tu mayor talento oculto que nadie conoce?',
    '¿Cuál es la cosa más estúpida que has hecho por llamar la atención?',
    '¿Tienes algún crush actualmente? Sin decir el nombre, ¿dónde lo conociste?',
    '¿Cuál es tu app más visitada y cuánto tiempo le dedicas al día?',
    '¿Cuál es el apodo más vergonzoso que te han puesto?',
    '¿Alguna vez hablaste solo/a en público sin darte cuenta?',
    '¿Cuál es la mentira más pequeña que dices con frecuencia?',
    '¿Qué haces cuando crees que nadie te está viendo?',
    '¿Alguna vez te enamoraste de un personaje ficticio? ¿Cuál?',
    '¿Cuál es tu mayor adicción que nadie sabe?',
    '¿Qué cosa de las que haces en privado te daría más vergüenza que alguien viera?',
    '¿Alguna vez le echaste la culpa a alguien más por algo que hiciste tú?',
    '¿Cuál es el rumor más raro que has escuchado sobre ti mismo/a?',
    '¿Tienes algún peluche u objeto de la infancia que todavía guardas?',
    '¿Cuál fue la última vez que lloraste y por qué?',
    '¿Qué es lo que más te da envidia de alguien del grupo?',
    '¿Cuál es tu comida basura favorita que comes en secreto?',
    '¿Alguna vez fingiste que te gustaba un regalo que te dieron?',
    '¿Cuál es el personaje famoso que más te atrae y que te da vergüenza admitir?',
    '¿Cuántas veces al día te miras al espejo?',
    '¿Cuál es la cosa más rara que has buscado en internet?',
    '¿Alguna vez enviaste un mensaje al destinatario equivocado? ¿Qué decía?',
    '¿Cuál es tu mayor complejo físico?',
    '¿Qué harías si tuvieras un día completamente solo/a sin que nadie te juzgara?',
    '¿Alguna vez le gustaste a alguien y no te diste cuenta hasta mucho después?',
    '¿Cuál es el momento más torpe que has tenido frente a alguien que te gustaba?',
    '¿Qué es lo más raro que has hecho cuando estabas solo/a en casa?',
    '¿Alguna vez escuchaste una conversación que no debías?',
    '¿Cuál es tu canción favorita para cantar en la ducha?',
    '¿Qué es lo que más te molesta de alguien del grupo pero nunca has dicho?',
    '¿Cuál es el trabajo más ridículo que harías por dinero?',
    '¿Alguna vez te has caído en público de forma épica? ¿Cómo fue?',
    '¿Qué es lo que más te avergüenza de tu pasado?',
    '¿Alguna vez te has colado en algún lugar sin permiso?',
    '¿Cuál es la mentira más creativa que has inventado para salir de un problema?',
    '¿Alguna vez has leído el diario o mensajes privados de alguien sin permiso?',
    '¿Cuál es tu mayor fobia irracional?',
    '¿Qué cosa has prometido que nunca has cumplido?',
    '¿Alguna vez tuviste un accidente vergonzoso en público del que nadie sabe?',
    '¿Cuál es la canción que más has repetido en tu vida y cuántas veces?',
    '¿Qué es lo que más te aburre pero finges que te encanta?',
    '¿Cuál es la cosa más cara que has roto y nunca admitiste?',
    '¿Alguna vez te has dormido en el baño? ¿Por qué?',
    '¿Cuál es el recuerdo más vergonzoso de la secundaria o preparatoria?',
    '¿Qué es lo que más extrañas de la infancia?',
    '¿Alguna vez comiste algo del piso aplicando la regla de los 5 segundos?',
    '¿Cuál es tu peor manía que la gente nota pero no te dice?',
    '¿Qué harías si te dieran un millón de dólares mañana?',
    '¿Cuál es el chiste más malo que conoces y aun así te ríes?',
    '¿Alguna vez fingiste no tener wifi para no responder a alguien?',
    '¿Cuál es la cosa más extraña que te da miedo y que parece ridícula?',
    '¿Qué es lo primero que piensas cuando conoces a alguien nuevo?',
    // --- LOTE MASIVO DE VERDADES SUAVES (60 NUEVAS) ---

    // --- VERGÜENZAS Y ANÉCDOTAS ---
    '¿Cuál es el mensaje de texto más vergonzoso que has enviado por error al grupo de tu familia?',
    '¿Alguna vez te has quedado atrapado/a en un baño público? ¿Cómo saliste?',
    '¿Qué es lo más ridículo que has hecho para llamar la atención de alguien en redes sociales?',
    '¿Has saludado a alguien en la calle pensando que lo conocías y resultó ser un extraño?',
    '¿Cuál es la caída más graciosa que has tenido en público?',
    '¿Alguna vez has fingido una llamada para evitar hablar con alguien en la calle?',
    '¿Qué es lo más raro que has hecho estando solo/a en casa y que te daría pena que alguien viera?',
    '¿Cuál es el video de YouTube más tonto que has visto más de 5 veces?',
    '¿Alguna vez te has reído en un momento inapropiado (como un examen o una reunión)?',
    '¿Qué es lo más "tacaño" que has hecho para ahorrar un poco de dinero?',
    '¿Cuál es la comida que preparas cuando tienes flojera y que se ve horrible pero sabe bien?',
    '¿Has usado la misma ropa interior dos días seguidos porque no tuviste tiempo de lavar?',
    '¿Cuál es el sueño más extraño que has tenido y que todavía recuerdas perfectamente?',
    '¿Alguna vez has buscado tu propio nombre en Google? ¿Qué encontraste?',
    '¿Qué es lo más infantil que sigues haciendo a tu edad actual?',

    // --- GUSTOS CULPOSOS Y SECRETOS INOCENTES ---
    '¿Qué canción te gusta tanto que te daría vergüenza que tus amigos vieran tu historial de Spotify?',
    '¿Cuál es la película "mala" que todo el mundo odia pero a ti te encanta?',
    '¿Qué serie de televisión para niños sigues viendo o verías de nuevo sin problemas?',
    '¿Cuál es tu combinación de comida más rara (ejemplo: papas fritas con helado)?',
    '¿A qué famoso/a seguías fanáticamente cuando eras más joven?',
    '¿Cuál es el objeto más inútil que tienes en tu cuarto pero que te niegas a tirar?',
    '¿Tienes algún ritual extraño antes de dormir?',
    '¿Cuál es el aroma más raro que te gusta oler (ejemplo: gasolina, barniz, tierra mojada)?',
    '¿Qué es lo que más te gusta comprar aunque sepas que no lo necesitas?',
    '¿Cuál es tu placer culposo favorito de domingo por la tarde?',

    // --- PERSONALIDAD Y OPINIONES ---
    '¿Si pudieras cambiar tu nombre por uno de un personaje histórico, cuál elegirías?',
    '¿Qué es lo primero que harías si te despertaras siendo del sexo opuesto por un día?',
    '¿Cuál es la habilidad más inútil que desearías tener a nivel experto?',
    '¿Si pudieras borrar una red social para siempre, cuál sería y por qué?',
    '¿Qué es lo que más te molesta que haga la gente en una primera cita?',
    '¿Prefieres ser un genio feo o un tonto muy guapo/a?',
    '¿Cuál es la palabra que siempre deletreas mal por más que lo intentes?',
    '¿Si fueras un sabor de helado, cuál serías según tu personalidad?',
    '¿Qué es lo más aventurero que has hecho fuera de tu zona de confort?',
    '¿Cuál es el mejor cumplido que te han dado y quién lo hizo?',

    // --- RELACIONES Y AMISTAD ---
    '¿Quién de este grupo crees que sobreviviría más tiempo en un apocalipsis zombie?',
    '¿A qué persona de aquí elegirías para que te ayude a esconder un tesoro?',
    '¿Cuál fue tu primera impresión de la persona que tienes a tu izquierda?',
    '¿Qué es lo que más valoras en una amistad de verdad?',
    '¿Has tenido un "crush" con un profesor/a en la escuela?',
    '¿Cuál es el regalo más feo que has recibido y qué cara pusiste al abrirlo?',
    '¿Si tuvieras que vivir en una isla desierta con alguien de aquí, a quién elegirías?',
    '¿Qué es lo que más te hace reír de la persona que tienes enfrente?',
    '¿Alguna vez has enviado un mensaje criticando a alguien y se lo enviaste a esa misma persona?',
    '¿Cuál es el apodo más tierno o ridículo que te han puesto tus padres?',

    // --- CURIOSIDADES ---
    '¿Qué es lo más valiente que has hecho en tu vida?',
    '¿Cuál es el lugar más raro donde te has quedado dormido/a?',
    '¿Qué harías si ganaras la lotería pero solo pudieras gastar el dinero en otras personas?',
    '¿Cuál es tu mayor miedo irracional hoy en día?',
    '¿Qué canción elegirías para que fuera el himno de tu vida?',
    '¿Cuál es la mentira más creativa que has dicho para faltar al trabajo o a la escuela?',
    '¿Qué es lo que más te emociona del futuro?',
    '¿Si pudieras viajar en el tiempo solo para ver un concierto, a cuál irías?',
    '¿Cuál es tu posesión más preciada que no cuesta dinero?',
    '¿Qué es lo que más te gusta de vivir en tu ciudad?',
    '¿Cuál es el animal que más te representa y por qué?',
    '¿Si pudieras ser invisible por una hora, a dónde irías?',
    '¿Qué es lo que siempre quisiste aprender pero nunca tuviste tiempo?',
    '¿Cuál es tu aplicación del celular que más te da vergüenza usar?',
    '¿Qué es lo primero que harías si fueras el presidente del mundo por un día?',
  ],
  retos: [
    'Imita a alguien del grupo sin decir su nombre hasta que adivinen quién es.',
    'Haz 15 sentadillas mientras cantas una canción de tu infancia.',
    'Envíale un corazón ❤️ al último contacto de tu WhatsApp sin explicación.',
    'Habla con acento extranjero por los próximos 3 minutos.',
    'Actúa como un robot con movimientos y voz por 1 minuto completo.',
    'Di 5 trabalenguas en menos de 30 segundos o pierdes.',
    'Llama a alguien al azar y canta cumpleaños feliz sin dar explicaciones.',
    'Haz una pose de superhéroe épica y mantenla 20 segundos.',
    'Baila sin música durante 30 segundos con toda la energía posible.',
    'Escríbele un mensaje ultra dramático de telenovela a alguien del grupo.',
    'Imita a un animal durante 30 segundos, el grupo adivina cuál.',
    'Di 3 cosas genuinamente buenas de cada persona del grupo.',
    'Muestra las últimas 5 fotos de tu galería al grupo.',
    'Habla sin usar la letra "a" por 1 minuto completo.',
    'Haz la mejor selfie ridícula posible y ponla de foto de perfil por 5 min.',
    'Haz una actuación dramática llorando sin lágrimas reales por 30 segundos.',
    'Inventa una canción sobre alguien del grupo en 1 minuto.',
    'Haz una reverencia exagerada cada vez que alguien te hable por 3 minutos.',
    'Deja que el grupo te peine el cabello como quiera por 1 minuto.',
    'Recita el abecedario al revés lo más rápido que puedas.',
    'Haz 10 flexiones de brazos en este momento.',
    'Imita a un influencer haciendo un video de "get ready with me" por 45 segundos.',
    'Describe a alguien del grupo usando solo nombres de animales.',
    'Canta la intro de tu serie favorita con toda la emoción posible.',
    'Haz una presentación de ventas de un objeto random que tengas cerca.',
    'Actúa como si fueras un presentador de noticias por 1 minuto.',
    'Muestra tu lista de reproducción más vergonzosa al grupo.',
    'Llama a tu mamá o papá y diles que los quieres mucho sin más explicación.',
    'Habla como villano de caricatura por los próximos 2 minutos.',
    'Haz el moonwalk de Michael Jackson por toda la habitación.',
    'Pon tu álbum de fotos de hace 5 años y muestra 3 fotos al azar.',
    'Improvisa un rap de 30 segundos sobre alguien del grupo.',
    'Actúa como si estuvieras en una entrevista de trabajo muy seria por 1 minuto.',
    'Haz una declaración épica de amor a un objeto cualquiera del cuarto.',
    'Cuenta un chiste malo que dure al menos 1 minuto.',
    'Imita al profesor más memorable que hayas tenido.',
    'Haz una pose de catálogo de ropa y mantenla 15 segundos.',
    'Describe tu día de hoy como si fuera una película de acción.',
    'Actúa como si fueras un chef famoso explicando cómo hacer un sándwich.',
    'Haz 3 mímicas de canciones populares para que el grupo las adivine.',
    'Muestra las notificaciones de tu teléfono ahora mismo.',
    'Inventa un trabalenguas en 30 segundos y dilo 3 veces seguidas.',
    'Actúa como un turista perdido preguntando cómo llegar al baño.',
    'Muéstrale al grupo el último meme que guardaste.',
    'Haz una oración con cada letra de tu nombre.',
    'Imita a un bebé tratando de hablar por 30 segundos.',
    'Canta cualquier canción pero reemplaza cada vocal con "e".',
    'Grita tu nombre completo a todo volumen.',
    'Actúa como si acabaras de ganar un Oscar por 45 segundos.',
    'Haz una rutina de baile de reggaetón de 30 segundos sin música.',
    'Llama a alguien por teléfono y habla con voz de pato todo el tiempo.',
    'Describe a un miembro del grupo como si fuera un personaje de cuento de hadas.',
    'Haz una pose de yoga que el grupo invente durante 20 segundos.',
    'Actúa como si un insecto invisible te estuviera persiguiendo por 30 segundos.',
    'Di el nombre de 10 países en menos de 10 segundos.',
    'Imita al presentador de tu programa de televisión favorito de infancia.',
    'Haz un monólogo de villano sobre por qué el grupo te ha decepcionado.',
    'Cambia tu tono de notificación al más ridículo posible.',
    'Describe tu vida en 5 palabras y que el grupo las adivine.',
    'Haz una imitación de cómo caminas tú mismo/a.',
    'Haz equilibrio con un objeto en la cabeza (como un cojín o libro) mientras caminas en círculo por 30 segundos.',
    'Actúa como un comentarista deportivo narrando lo que está pasando en la habitación en este momento.',
    'Pide permiso a un objeto inanimado (una silla o lámpara) antes de tocarlo durante las próximas dos rondas.',
    'Usa tus calcetines en las manos como si fueran marionetas y mantén una breve conversación entre ellas.',
    'Haz una rima rápida con el nombre de cada persona presente en el grupo.',
    'Inventa un nombre de superhéroe y un superpoder absurdo para cada integrante del grupo.',
    'Haz todos tus movimientos en cámara lenta extrema durante el próximo minuto.',
    'Lee los ingredientes de cualquier etiqueta de comida o bebida con voz de poema dramático.',
    'Imita cómo crees que suena un alienígena tratando de pedir una pizza por teléfono.',
    'Cuenta una historia de terror de 30 segundos sobre un objeto común que esté sobre la mesa.',
    'Camina hacia atrás cada vez que tengas que moverte de tu sitio por los próximos 5 minutos.',
    'Susurra absolutamente todo lo que digas durante los próximos 2 minutos.',
    'Dile un "dato curioso" totalmente inventado al grupo con mucha seguridad y convicción.',
    'Intenta lamerte el codo durante 20 segundos frente a todos los presentes.',
    'Quédate como una estatua y no te muevas para nada hasta que alguien del grupo diga tu nombre completo.',
    'Habla como si estuvieras debajo del agua (tapándote la nariz y moviendo los labios) por el próximo minuto.',
    'Mantén un duelo de miradas con la persona a tu derecha; el primero que parpadee pierde.',
    'Intenta mantener una cuchara en equilibrio sobre tu nariz por al menos 15 segundos.',
    'Dibuja a alguien del grupo en un papel en menos de 30 segundos y que los demás adivinen quién es.',
    'Hazle un cumplido a la persona de tu izquierda usando únicamente palabras que rimen.',
    'Aplaude con entusiasmo cada vez que alguien se ría durante los próximos 2 minutos.',
    'Habla de ti mismo en tercera persona hasta que sea tu próximo turno en el juego.',
    'Actúa como si fueras un mimo atrapado en una caja invisible durante 45 segundos.',
    'Inventa un nuevo paso de baile, ponle un nombre gracioso y enséñaselo al resto del grupo.',
    'Reacciona con un "¡Wow!" exagerado a cualquier cosa que alguien diga durante un minuto completo.',
    'Imita el sonido y el movimiento de una lavadora en ciclo de centrifugado por 30 segundos.',
    'Pretende que tienes un amigo invisible a tu lado y preséntalo formalmente a cada miembro del grupo.',
    'Haz una "pasarela de moda" usando una manta, sábana o toalla como si fuera alta costura.',
    'Di la palabra "miau" al final de cada frase que digas durante los próximos 2 minutos.',
    'Intenta realizar un truco de magia sencillo con cualquier objeto cercano (no importa si falla).',
    'Habla como un pirata en cada una de tus intervenciones durante las próximas dos rondas.',
    'Haz un reporte del clima exagerado sobre lo que está pasando en la habitación justo ahora.',
    'Mantente en equilibrio sobre una sola pierna durante un minuto completo; si te caes, reinicias el tiempo.',
    'Da una "Charla TED" de 45 segundos sobre por qué el cereal es (o no es) una sopa.',
    'Camina como un pingüino cada vez que tengas que moverte de tu sitio por los próximos 5 minutos.',
    'Ponte la camiseta al revés (lo de atrás para adelante) y déjala así por el resto del juego.',
    'Hazte un sombrero con papel o papel de aluminio y úsalo con orgullo durante las próximas tres rondas.',
    'Actúa como un gato que se está acicalando durante 30 segundos, ignorando por completo al grupo.',
    'Saluda a cada persona de la habitación chocando los codos en lugar de las manos.',
    'Haz el sonido de un motor de coche viejo intentando arrancar cada vez que alguien diga la palabra "reto".',
    'Habla con una voz extremadamente aguda (como si hubieras inhalado helio) durante el próximo minuto.',
    'Da 10 vueltas sobre ti mismo y luego intenta caminar en línea recta por la habitación.',
    'Canta absolutamente todo lo que digas durante los próximos dos minutos.',
    'Deja que la persona a tu derecha te dibuje un pequeño bigote con algo lavable y no te lo quites hasta el final.',
    'Posa como una estatua de museo famosa y deja que el grupo te ponga un "título" artístico.',
    'Intenta hacer reír a la persona frente a ti en 30 segundos usando solo gestos, sin tocarla.',
    'Actúa como si acabaras de ganar la lotería, pero mantén el secreto haciendo solo gestos de victoria.',
    'Describe una fruta sin decir su nombre ni su color hasta que alguien del grupo la adivine.',
    'Muévete por la habitación como si el piso fuera lava ardiente durante el próximo minuto.',
    'Haz una imitación de un cantante de ópera al que le da un ataque de estornudos en plena nota alta.',
    'Realiza una "muerte dramática" digna de un Oscar en medio de la sala.',
    'Actúa como una gallina que acaba de poner un huevo y está muy orgullosa de ello por 30 segundos.',
    'Atraviesa la habitación moviéndote como un ninja sigiloso, tratando de no hacer ni un solo ruido.',
    'Inventa una porra de 10 segundos animando a la persona que tienes a tu izquierda.',
    'Intenta tocarte la punta de la nariz con la lengua durante 20 segundos frente a todos.',
    'Habla como si tuvieras un malvavisco gigante imaginario en la boca durante el próximo minuto.',
    'Crea un "saludo secreto" complejo con la persona a tu derecha y ejecútenlo perfectamente.',
    'Intenta hacer malabares con tres objetos pequeños y ligeros (como cojines) durante 20 segundos.',
    'Cuenta una historia breve de 30 segundos usando únicamente nombres de marcas famosas.',
    'Sé el líder de "Simón dice" durante un minuto y haz que todos sigan tus órdenes ridículas.',
    'Actúa como un asistente de vuelo dando las instrucciones de seguridad de la habitación.',
    'Lee el último mensaje que recibiste como si fueras un actor dramático de la época de Shakespeare.',
    'Intenta tocarte los dedos de los pies sin doblar las rodillas y mantén la posición 20 segundos.',
    'Da una charla motivacional de 45 segundos al grupo como si fueras un entrenador de fútbol en el descanso.',
    'Improvisa un comercial de 30 segundos para un producto imaginario que "cura la pereza".',
    'Silba una canción famosa y no pares hasta que alguien del grupo adivine cuál es.',
    'Actúa como un detective de película antigua investigando la "misteriosa" desaparición de un objeto de la mesa.',
    'Haz de Guardia Real del Palacio de Buckingham (sin moverte ni reírte) durante 1 minuto mientras los demás intentan distraerte.',
    'Describe lo último que comiste como si fueras un crítico de comida de una revista de ultra lujo.',
    'Salta como una rana alrededor del círculo del grupo dos veces seguidas.',
    'Ladra como un perrito pequeño cada vez que alguien diga tu nombre durante los próximos 3 minutos.',
    'Pretende que eres un crítico de alta costura y comenta el "estilo" de los zapatos de cada persona en la sala.',
    'Intenta dibujar a la persona de enfrente usando tu mano no dominante en menos de 1 minuto.',
    'Actúa como si estuvieras en una montaña rusa muy rápida durante 30 segundos (con gritos incluidos).',
    'Da un discurso de 30 segundos defendiendo por qué la pizza con piña es (o no es) la mejor creación de la historia.',
    'Realiza una danza interpretativa de 30 segundos sobre lo que sientes cuando tienes mucha hambre.',
    'Habla únicamente haciendo preguntas durante los próximos 2 minutos (si afirmas algo, pierdes).',
    'Actúa como un niño pequeño haciendo un berrinche porque le dijeron que no hay postre.',
    'Haz el reporte del clima para mañana usando únicamente señas y gestos, sin decir ni una sola palabra.',
    'Camina de un lado a otro de la habitación como si fueras un cangrejo.',
    'Pretende que eres una estrella de rock dando un concierto mundial y usa un objeto cercano como micrófono.',
    'Describe la trama de tu película favorita usando solo onomatopeyas y sonidos (sin palabras).',
    'Actúa como si estuvieras en una película de cine mudo durante el próximo minuto completo.',
    'Intenta mantener un bolígrafo en equilibrio entre tu nariz y tu labio superior (como un bigote) por 20 segundos.',
    'Pretende que eres un fantasma que intenta asustar al grupo, pero que en realidad es extremadamente torpe.',
    'Dirige una sesión de "yoga para perezosos" donde todos los ejercicios se deben hacer sentados o acostados.',
    'Actúa como un reloj de pared y haz "tic-tac" rítmicamente cada vez que alguien deje de hablar.',
    'Describe a la persona de tu derecha como si fuera una nueva especie animal recién descubierta en la selva.',
    'Intenta decir una frase larga y seria mientras te sujetas la lengua con los dedos.',
    'Haz un avión de papel y lánzalo; si no vuela al menos 2 metros, debes hacer 5 saltos de tijera.',
  ],
};
